spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/alo-ute}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:hoang1808}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: ${JWT_SECRET:i5dcv0ucg77ltbae3l8s4b4c95efjoze}
    expiration: ${JWT_EXPIRATION:300000}

server:
  port: ${SERVER_PORT:8080}
